### ISSUE TITLE
Error retreiving or downloading

### ISSUE THREAD

**Issue by MoBOatGVA** [jackwilsdon/plex_download#1]
Hi,

this app was working fine but since today, I noticed the following error message :

> plex_download: error: HTTPSConnectionPool(host='plex.tv', port=443): Max retries exceeded with url: /users/sign_in.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7ff6665d2ed0>: Failed to establish a new connection: [Errno 111] Connection refused',))

Any idea how to fix this issue ?

The command was : `plex_download -s server ubuntu linux-ubuntu-x86_64`

**Comment by jackwilsdon** [comment]
Well that's different! I'm not quite sure how that is even possible, as we never actually call [`Client#login`](https://github.com/jackwilsdon/plex_version/blob/67b20e9d51dda6a0b2ea95e1ec5c27542d21b364/plex_version/client.py#L42) from [plex_version](https://github.com/jackwilsdon/plex_version).

Could you provide the output of `plex_download -v`?

**Comment by jackwilsdon** [comment]
I've also just realised that the error means you can't actually reach the HTTPS version of [plex.tv](https://plex.tv). Can you visit it in a browser? What response do you get from visiting https://plex.tv/users/sign_in.json?

**Comment by MoBOatGVA** [comment]
Thanks for your answer.

According your suggestions, I found out the issue : pfBlockerNG on my pfSense firewall.
I'm using some GeoIP blocking and I guess I need to dig to open the correct URL.

So not an issue with your app.

BTW, Thanks for your work, really like it.

**Comment by jackwilsdon** [comment]
Thanks! Glad you managed to resolve the issue.

I've released a new version (1.1.0) with support for the `-v` flag (verbose), which should help with any issues in the future.
